name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential pkg-config libwayland-dev libxkbcommon-dev libxcursor-dev libasound2-dev

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: "ubu"

    - name: Run tests
      run: cargo test --release
    - name: Build
      run: cargo build --release

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: chip-8-linux-build
        path: target/release/chip-8
        if-no-files-found: error
